services:
  app:
    build: .
    container_name: finance-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8013:8013"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs